(in-package #:мастер)

(defvar *polling* t)

(defun start ()
  (format t "[master] Загружаем потоки...~%")
  (загрузить-все-потоки)
  (setf *polling* t)
  (poll-loop 0))

(defun poll-loop (offset)
  (when *polling*
    (handler-case
        (let* ((result (get-updates :offset offset :timeout 30))
               (updates (cdr (assoc :result result))))
          (if (null updates)
              (poll-loop offset)
              (let ((max-id offset))
                (dolist (upd updates)
                  (let ((id (cdr (assoc :update_id upd))))
                    (when (> id max-id) (setf max-id id)))
                  (обработать-update upd))
                (poll-loop (+ max-id 1)))))
      (error (e)
        (format *error-output* "[master] Ошибка в poll-loop: ~A~%" e)
        (sleep 2)
        (poll-loop offset)))))

(defun обработать-update (update)
  (cond
    ((assoc :message update)
     (let* ((msg (cdr (assoc :message update)))
            (chat (cdr (assoc :chat msg)))
            (chat-id (cdr (assoc :id chat)))
            (text (cdr (assoc :text msg))))
       (when (stringp text)
         (let ((resp (обработать-команду chat-id text)))
           (send-message chat-id resp))))
     t)
    ((assoc :callback_query update)
     (let* ((cb (cdr (assoc :callback_query update)))
            (chat-id (cdr (assoc :id (cdr (assoc :message cb)))))
            (data (cdr (assoc :data cb)))
            (resp (обработать-команду chat-id data)))
       (answer-callback-query (cdr (assoc :id cb)))
       (send-message chat-id resp))
     t)
    (t
     (format *error-output* "[master] Неизвестный update: ~A~%" update)
     nil))
